version: "3.9"
services:
  server:
    build: backend
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - "./backend/db.sqlite:/project/db.sqlite"
      - "./downloader/files:/project/files"
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
  frontend:
    build: frontend
    ports:
      - "127.0.0.1:8100:80"